### ISSUE TITLE
website fails when referencing repo with new generated manifest.bioimage.io.json

### ISSUE THREAD

**Issue by paulhfu** [bioimage-io/bioimage-io-models#44]
I compiled the ```manifest.bioimage.io.yaml``` with the attached ```compile_model_manifest.py```. The branch was equal to the master branch. I noticed that during compiling some fetches were failing.
When loading the website with https://bioimage.io/#/?repo=paulhfu%2Fbioimage-io-models%2Ftree%3D3D3dunet_nuclei 
i am greeted with 
```Failed to fetch manifest file from the repo: SyntaxError: JSON.parse: unexpected non-whitespace character after JSON data at line 1 column 4 of the JSON data.``` 
and the website stays empty.

**Comment by oeway** [comment]
Hi, I think that’s because the url format is incorrect. Remove /tree from
your url works:
https://bioimage.io/#/?repo=paulhfu%2Fbioimage-io-models%2F3dunet_nuclei

The correct format is ‘repo=user/repo/branch’.

**Comment by paulhfu** [comment]
Thanks @oeway . That was it.
