### ISSUE TITLE
Cover image of the models are not show properly

### ISSUE THREAD

**Issue by FynnBe** [bioimage-io/bioimage-io-models#6]
somehow my changes (https://github.com/bioimage-io/models/commit/ad8d9772e830d69597e6020eb0c1f3f01bb3071c) didn't make it all the way through to https://bioimage.io/

am I missing something?

**Comment by oeway** [comment]
Hey, sometimes Github takes sometime to serve newly committed files, and the browser may also have cache which take a while to update. However, here, I just checked that your changes are actually reflected, except I forgot to resolve the relative path to your cover image.

**Comment by oeway** [comment]
Hey @FynnBe It should work now, check it out: https://bioimage.io/

**Comment by FynnBe** [comment]
Awesome, allow me to recycle this issue for asking you about the exact image format... the cover image I uploaded was exactly 2:1, but there is some free space at the bottom... ?
![image](https://user-images.githubusercontent.com/15139589/75516592-2294da80-59fd-11ea-990d-79757c6d732a.png)

**Comment by oeway** [comment]
Hi @FynnBe thanks for pointing this out, this is because I haven't get time to optimize the card display, the current card width are adjusted according to some percentage of the screen width. 

Let's keep this issue open, but I will change the title.
