### ISSUE TITLE
Renaming 'master' branch to 'main'

### ISSUE THREAD

**Issue by FynnBe** [bioimage-io/bioimage-io-models#63]
Should we just go ahead and renaming the main branch and fix broken links afterwards or is there a need to investigate this and change synchronously? If we continue with the renaming of 'master' branches now and quickly it should latest be in a working state again at the end of the week...

@oeway @k-dominik @constantinpape , any objections to an immediate renaming?

**Comment by oeway** [comment]
Go ahead! I will do it for the bioimage.io repo.

Make sure you also changed the github actions script.
